### ISSUE TITLE
parrot error

### ISSUE THREAD

**Issue by Niterux** [Noryea/fast-items-fabric#2]
there is error when the game starts up about parrots or smth
https://mclo.gs/o2sMdKO

Minecraft 1.20.1
Quilt Loader 0.20.2
Fabric API 0.88.1+1.20.1
FastAnim 1.6
no other mods

**Comment by Niterux** [comment]
i posted on the wrong git repo

**Comment by Noryea** [comment]
what😂

**Comment by Niterux** [comment]
i may be stupid
